Repository HYF-Class20/agile-development-group3-hyf-redesign, pull requests merged in 2023-04, with the labels that each got.

#2 Added communication plan. Might needs further rewriting later on.
  planning/communication.md
Labels: documentation

#3 planning/added-readme-md
  planning/README.md
Labels: documentation

#7 planning/constraints-md-adding constraints.md
  planning/constraints.md
Labels: documentation

#5 planning/readme-md-update-correct-md-file
  README.md
Labels: documentation

#17 planning/user-persona-add user-persona-md file
  planning/user-personas.md
Labels: documentation

#15 html/main page/inviting image with header
  pages/another-page.html
  pages/main-page.html
Labels: html

#18 css/main-page/inviting-image-with-header
  styles/index.css
Labels: css

#24 Planning/constraints md -updaing -external -part
  planning/constraints.md
Labels: documentation

#27 planning/update-backlog-md
  planning/backlog.md
Labels: documentation

#30 planning/designs-md-adding wireframe fo homepage
  planning/assets/wireframe-homepage.png
  planning/design.md
Labels: documentation

#36 planning/designs-md adding wireframe for the programe page
  planning/assets/wireframe-programing.svg
  planning/design.md
Labels: documentation

#45 styles/css update volunteer.css-add webpage assets - fix links -fix img
  pages/volunteer.html
  public/images/icons/fb.svg
  public/images/icons/git.svg
  public/images/icons/linkedin.svg
  public/images/icons/twitter.svg
  styles/volunteer.css
Labels: css

#47 pages/html/ add digitalent.HTML & the programe.html and add more webp…
  pages/digitalent.html
  pages/theprogram.html
  pages/volunteer.html
  styles/other-pages.css
Labels: html

#49 pages/html/ update indext.HTML and add more webpage asstes
  index.html
  public/images/pictures/home-intro.jpg
  styles/styles.css
Labels: html
